baseURL = "https://pdxjohnny.github.io"

title = "pdxjohnny's blog"
languageCode = "en-us"
defaultContentLanguage = "en"

theme = "axiom"

paginate = 100
canonifyURLs = false
summaryLength = 40
rssLimit = 100
enableEmoji = false
enableRobotsTXT = true
pluralizelisttitles = false

[permalinks]
posts = "/:filename"

[params]
mainSections = ["posts", "about"]
copyrightYear = 2016
# Go Reference time: Mon Jan 2 15:04:05 MST 2006
dateFormat = "Jan 2, 2006 3:04PM"
highlight = "dark"

[params.brand]
domain = "pdxjohnny.github.io"
email = "johnandersenpdx@gmail.com"

[params.social]
github = "https://github.com/pdxjohnny"
twitter = "https://mastodon.social/@pdxjohnny"
linkedin = "https://www.linkedin.com/in/john-andersen-7a72b555/"
youtube = "https://www.youtube.com/@dffml9083/playlists"
footer = ["twitter", "github", "youtube", "linkedin"]

[params.logo]
inline = false
path = "images/avatar@2x.jpeg"

[params.services]
analyticsId = "UA-160259978-2"
adwordsId = ""
adsenseId = ""
adsenseAdSlotId = ""
adsenseLoad = ""
adwordsConversionId = ""
adwordsConversionValue = 0
facebookApp = ""
facebookPixel = ""
disqusShortname = ""

[params.image]
width = "2048"
height = "1024"
faviconIco = "favicon.ico"
faviconAlt = "image/brand/favicon.png"
icon1To1 = "image/brand/icon-1-1.png"
icon2To1 = "image/brand/icon-2-1.png"
default = "image/page-default.webp"

[params.font]
type = ""
path = ""
files = []

[params.cdn]
provider = "local"
type = "image"

[outputs]
home = ["HTML", "ATOM"]
section = ["HTML"]
taxonomy = ["HTML"]
taxonomyTerm = ["HTML"]

[outputFormats]
[outputFormats.ATOM]
name = "ATOM"
baseName = "feed"
mediaType = "application/atom+xml"

[mediaTypes]
[mediaTypes."application/atom+xml"]
suffixes = ["atom"]

[markup]
[markup.goldmark]
[markup.goldmark.extensions]
definitionList = false
footnote = true
linkify = true
strikethrough = false
table = true
taskList = false
typographer = false
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.parser]
attribute = false
[markup.highlight]
codeFences = true
noClasses = false
tabWidth = 2
# lineNos = true
# lineNumbersInTable = false

[menu]
[[menu.main]]
url = "/posts/"
name = "Posts"
weight = 1

[[menu.main]]
url = "/about/"
name = "About"
weight = 2

[[menu.main]]
url = "/MaryisGod/"
name = "💊"
weight = 3

[[menu.foot]]
url = "/posts/"
name = "Posts"
weight = 1

[[menu.foot]]
url = "/about/"
name = "About"
weight = 2

[[menu.foot]]
url = "/MaryisGod/"
name = "💊"
weight = 3

[languages]
[languages."en"]
weight = 1
languageName = "English"
