name: Spell Check and Create PR

on:
  push:
    branches:
      - dev

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Install codespell
      - name: Install codespell
        run: |
          python -m pip install --upgrade pip
          pip install codespell

      # Run codespell on all .md files
      - name: Run codespell
        run: |
          set +e
          codespell --write-changes --skip="./.git" .

      # Check if there are any changes made by codespell
      - name: Check for spelling corrections
        run: |
          if git diff --quiet; then
            echo "No spelling errors found."
            exit 0
          else
            echo "Spelling errors corrected. Proceeding to create a PR."
          fi

      # Commit the changes and create a pull request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Fix spelling errors"
          branch: spelling-fixes
          title: "Fix spelling errors in .md files"
          body: |
            This pull request fixes spelling errors found in markdown files.
          base: dev
